import { NavItem } from '@/types';
import {
    BarChart,
    Building2,
    CornerDownRight,
    FileEdit,
    Heart,
    Home,
    LayoutGrid,
    MapPinned,
    Newspaper,
    PackagePlus,
    ScrollText,
    Settings,
    ShieldAlert,
    User,
} from 'lucide-react';

export const platformItems: NavItem[] = [
    {
        title: 'Home',
        href: '/',
        icon: Home,
        roles: 'public',
        description: 'Go back to the main homepage.',
    },
    {
        title: 'About',
        href: '/about',
        icon: Building2,
        roles: 'public',
        description: 'Learn more about our company.',
    },
    {
        title: 'Menu',
        href: '/products',
        icon: ScrollText,
        roles: 'public',
        description: 'Explore our delicious food and beverage options.',
        children: [
            {
                title: 'All Products',
                href: '/products',
                icon: CornerDownRight,
                description: 'Browse all available items in our menu.',
                roles: 'public',
            },
            // {
            //     title: 'Ordering',
            //     href: '/product/ordering',
            //     icon: ShoppingCart,
            //     description: 'Place your order for pickup or delivery.',
            //     roles: ['user', 'admin', 'author'],
            // },
            {
                title: 'Wishlist',
                href: '/products/wishlist',
                icon: Heart,
                description: 'Save your favorite items for later.',
                roles: ['user', 'admin', 'author'],
            },
            {
                title: 'Charts',
                href: '/product/charts',
                icon: BarChart,
                description: 'View sales and product performance charts.',
                roles: ['admin', 'author'],
            },
        ],
    },
    {
        title: 'Articles',
        href: '/blog',
        icon: Newspaper,
        roles: 'public',
        description: 'Read our latest news and blog posts.',
    },
    {
        title: 'Location',
        href: '/location',
        icon: MapPinned,
        roles: 'public',
        description: 'Find our physical store locations and contact info.',
    },
    {
        title: 'Dashboard',
        icon: LayoutGrid,
        roles: ['admin', 'author'],
        description: 'Access your administrative and author tools.',
        children: [
            {
                title: 'Overview',
                href: '/dashboard',
                icon: CornerDownRight,
                description: 'See a quick summary of your site activity.',
                roles: ['admin', 'author'],
            },
            {
                title: 'Manage Users',
                href: '/admin/users',
                icon: User,
                description: 'Add, edit, or delete user accounts.',
                roles: ['admin'],
            },
            {
                title: 'Product',
                href: '/admin/products',
                icon: PackagePlus,
                description: 'Create, publish, and manage your products.',
                roles: ['admin'],
            },
            {
                title: 'Article',
                href: '/editor/articles',
                icon: FileEdit,
                roles: ['admin', 'author'],
                description: 'Manage your articles and review content contributions.',
            },
            {
                title: 'Notification',
                href: '/editor/notifications',
                icon: FileEdit,
                description: 'Create, publish, and manage your articles.',
                roles: ['admin', 'author'],
            },
            {
                title: 'Settings',
                href: '/settings/profile',
                icon: Settings,
                description: 'Configure application settings and preferences.',
                roles: ['admin'],
            },
        ],
    },
];

export const footerNavItems: NavItem[] = [
    {
        title: 'Kebijakan Privasi',
        href: '/kebijakan-privasi',
        icon: ShieldAlert,
        roles: 'public',
        description: 'Baca kebijakan privasi kami untuk melindungi data Anda.',
    },
];
